services:
  postgres:
    container_name: vti_ms_app
    image: postgres
    environment:
     POSTGRES_USER: ${DB_NAME}
     PGADMIN_PASSWORD: ${DB_PASSWORD}
     PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/data
    networks:
      - vti_ms_app-net
    ports:
      - '5432:5432'
    restart: unless-stopped
  pgadmin:
    container_name: vti-ms-app-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG-SERVER-MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - vti_ms_app-net
    ports:
      - '5050:80'
    restart: unless-stopped



networks:
 vti_ms_app-net:
   driver: bridge

volumes:
  postgres:
  pgadmin: